#------------------------------------------------------------------------------
# NK Common Makefile
#
# Author        : Sebastien LAURENT
# Date          : 03/09/2011
#

# Common Directories

OBJDIR=.obj
DEPDIR=.dep

# Common tools
CC=gcc
AR=ar
RANLIB=ranlib
LD=ld
OBJCOPY=objcopy

