#!/bin/bash

###########
# Usage
usage() {
	echo "Usage: mkdisk [image]"
	echo "C/H/S 64/255/63"
}

if [ $# -ne 1 ] 
then 
	usage
	exit 1	
fi

# nsect = 64*255*63

dd if=/dev/zero of=$1 bs=512 count=1028160

